AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Parameters:
  RunId:
    Type: String
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: "lambda-test-bucket-192168255261-us-east-2"
        S3Key: !Sub lambdatest_${RunId}.zip
      Handler: lambda_function.lambda_handler
      Role: !GetAtt RoleLambda.Arn
      Runtime: python3.9
      FunctionName: test-function
  
  RoleLambda:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      RoleName: Lambda-test-Role
      Description: Selected Policies to run Lambdas
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole